name: 'Spectra Program'
on: 
  workflow_dispatch:
  push:
    branches:
      - main


jobs:  
  build:
    runs-on: ubuntu-latest
    name: 'Build and push docker image'
    steps:
      - name: 'Checkout code'
        uses: actions/checkout@v4

      - name: 'Say hello'
        run: echo "Hello, world! I am building the Spectra program."