name: 'Spectra Program'
on: 
  workflow_dispatch:
  push:
    branches:
      - main
jobs:  
  build:
    runs-on: ubuntu-latest
    name: 'Build and push docker image'
    steps:
      - name: 'Checkout code'
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_SECRET }}


      - name: 'Build Docker image'
        env:
          DOCKER_REGISTRY: 'pangw1n/spectra'
          # IMAGE_TAG: ${{ github.sha }}
          IMAGE_TAG: 'latest'
        run: |
          docker build -t ${DOCKER_REGISTRY}:${IMAGE_TAG} .
          docker push ${DOCKER_REGISTRY}:${IMAGE_TAG}